spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=journal;encrypt=true;trustServerCertificate=true
    username: sa
    password: YourStrong!Passw0rd
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.SQLServerDialect
  flyway:
    enabled: true